version: '3'

services:
  # Spring Boot 应用服务
  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db

  # MySQL 服务
  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: baseTaste
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
